words = [
  "Astro",
  "checkhealth",
  "ClaudeCode",
  "codeium_os",
  "colorscheme",
  "config",
  "cterm",
  "cursorcolumn",
  "cursorline",
  "DAP",
  "edheltzel",
  "EdHeltzel",
  "Edheltzel",
  "fd",
  "folke",
  "Github",
  "github",
  "Gitsigns",
  "gopls",
  "heltzel",
  "Heltzel",
  "https",
  "js",
  "keymap",
  "keymaps",
  "laststatus",
  "LazyGit",
  "Lazygit",
  "lazygit",
  "LazyVim",
  "lazyvim",
  "LSP",
  "lua",
  "lualine",
  "neoed",
  "Neovim",
  "nvim",
  "OpenCode",
  "ripgrep",
  "spelllang",
  "statusline",
  "Supermaven",
  "swapfile",
  "TypeScript",
  "undodir",
  "undofile",
  "VSCode",
  "VSpaceCode",
  "Vue",
  "xclip",
]
